language: php
php:
  - '8.1'
dist: focal
os: linux
install:
  - sh ./scripts/install.sh
script:
  - sh ./scripts/unit-test.sh
  - sh ./scripts/lint.sh
  - sh ./scripts/static-analysis.sh
after_script:
  - sh ./scripts/package.sh
notifications:
  email:
    recipients:
      - yaosiang.su@104.com.tw
    on_success: always
    on_failure: always
